### ISSUE TITLE
Node.new(something) is not assigning relations

### ISSUE THREAD

**Issue by ProGM** [neo4jrb/neo4j#1065]
Given this nodes:
```ruby
class Node1
  include Neo4j::ActiveNode
  has_one :out, :node2, type: :relation
end

class Node2
  include Neo4j::ActiveNode
  has_many :in, :node1, type: :relation
end
```

I noticed that, when I instantiate Node1 passing Node2 as parameter, it's not assigned:

```ruby
node2 = Node2.create
node1 = Node1.new(node2: node2)
node1.node2 # => nil
```

Instead if I `create` it, instead, it seems to work:

```ruby
node2 = Node2.create
node1 = Node1.create(node2: node2)
node1.node2 # => #<Node2 ... >
```

Is it the correct behavior?

**Comment by cheerfulstoic** [comment]
I think perhaps that there is an issue with the gem, but there's also a bug in your code.  The `origin` option should refer to the association's name, not the Neo4j relationship type.  So if your case the `node1` association should look like:

```ruby
  has_many :in, :node1, origin: :node2
```

Alternatively you could just specify the `type` again:

```ruby
  has_many :in, :node1, type: :relation
```

When I make this change I get:

```ruby
2.2.3 :018 > node1 = Node1.create
 CYPHER 76ms CREATE (n:`Node1` {props}) RETURN ID(n) | {:props=>{:uuid=>"357237c2-1618-45c4-bdde-b509be274a3b", :created_at=>1450102958, :updated_at=>1450102958}}
 => #<Node1 uuid: "357237c2-1618-45c4-bdde-b509be274a3b", created_at: Mon, 14 Dec 2015 14:22:38 +0000, updated_at: Mon, 14 Dec 2015 14:22:38 +0000>
2.2.3 :019 > node2 = Node2.new(node1: node1)
 => #<Node2 uuid: nil, created_at: nil, updated_at: nil>
2.2.3 :020 > node2.persisted?
 => false
2.2.3 :021 > node2.node1
 => #<AssociationProxy @query_proxy=#<QueryProxy Node2#node1 CYPHER: "MATCH node2 WHERE (ID(node2) IS NULL) MATCH node2<-[rel1:`relation`]-(result_node1:`Node1`)">>
```

I'm thinking, though, that associations on unpersisted objects should never return an `AssociationProxy` because there would never be a starting point to the query that would be executed.  For example when I call `node2.node1.to_a` I get:

```
2.2.3 :023 > node2.node1.to_a
 Node2#node1 33ms
  MATCH node2
  WHERE (ID(node2) IS NULL)
  MATCH node2<-[rel1:`relation`]-(result_node1:`Node1`)
  RETURN result_node1
```

Which is ridiculous because you'll never have `ID()` of any node be `NULL`.  I wonder if @subvertallchris agrees with my logic here.

Another point to make is that `node1` is a `has_many` association, so the syntax to set it up with `new` or `create` would be as an Array like:

```ruby
node2 = Node2.new(node1: [node1])
```

But still, I get an `AssociationProxy`.

**Comment by ProGM** [comment]
Sorry, I really did a mess with my example. I switched `Node1` and `Node2` names.

I fixed it in the first post, but still I'm having the issue.
Please take a look.

**Comment by cheerfulstoic** [comment]
Yup, I see that it's returning `nil`.  Thanks for the update.  I think it's still the same problem.  With `has_many` it was returning an `AssociationProxy` and with `has_one` it tries to return one object.  It's making a similar query:

```
 Node1#node2 77ms
  MATCH node1
  WHERE (ID(node1) IS NULL)
  MATCH node1-[rel1:`relation`]->(result_node2:`Node2`)
  RETURN result_node2
```

For now, if you call `node1`.save and then call `node1.node2` you'll get the right object.  I hope that helps you work around your issue for the moment.

I'd like to hear my colleague @subvertallchris 's opinion and then I think we can fix this in relatively short order.

**Comment by ProGM** [comment]
Oh, fine!
Thank you :)

**Comment by subvertallchris** [comment]
Yup, the change you suggested to `AssociationProxy` seems like the thing!

**Comment by cheerfulstoic** [comment]
Ok, I think I've fixed it.  Could you try this in your `Gemfile`?

    gem 'neo4j', github; 'neo4jrb/neo4j', branch: '6.0.x'

**Comment by ProGM** [comment]
I tested in my real app:

```bash
irb(main):020:0> a = Article.new(creator: Person.first)
 CYPHER 6ms MATCH (n:`Person`) RETURN n ORDER BY n.uuid LIMIT {limit_1} | {:limit_1=>1}
=> #<Article uuid: nil, abstract: nil, created_at: nil, pg_id: nil, slug: nil, title: nil, updated_at: nil>
irb(main):021:0> a.creator
 Article#creator 9ms MATCH article WHERE (ID(article) IS NULL) MATCH article-[rel1:`creator`]->(result_creator:`Person`) RETURN result_creator
=> #<Person uuid: "0384906e-2faa-44b7-a267-d0aaa2977891", created_at: Wed, 16 Dec 2015 14:54:37 +0000, first_name: "John", last_name: "Doe 7", pg_id: 8, updated_at: Wed, 16 Dec 2015 14:54:37 +0000, username: "john-doe-7">
```

It seems ok :+1:

**Comment by cheerfulstoic** [comment]
Awesome, I also just released it as 6.0.2, so that should fix it for you.  Thanks!
